---
abstract: 'Matrix operations and LUP decomposition.'
author:
  - 'Daniel Șuteu <trizen@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-MatrixLUP
provides:
  Math::MatrixLUP:
    file: lib/Math/MatrixLUP.pm
    version: '0.01'
recommends:
  Math::AnyNum: '0.31'
requires:
  Carp: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/trizen/Math-MatrixLUP/issues
  homepage: https://github.com/trizen/Math-MatrixLUP
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: https://github.com/trizen/Math-MatrixLUP
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
